# Generated by Django 5.2.3 on 2025-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksef_reference_number', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Numer referencyjny KSeF')),
                ('ksef_status', models.CharField(blank=True, help_text='Status przetwarzania faktury w KSeF (np. Wysłano, Przetworzono, Błąd)', max_length=20, null=True, verbose_name='Status w KSeF')),
                ('ksef_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wysłania do KSeF')),
                ('ksef_session_id', models.CharField(blank=True, help_text='Numer referencyjny sesji po wysłaniu faktury', max_length=40, null=True, verbose_name='ID sesji KSeF')),
                ('ksef_processing_description', models.TextField(blank=True, help_text='Zawiera komunikaty o błędach lub sukcesie z KSeF', null=True, verbose_name='Opis przetwarzania KSeF')),
            ],
        ),
    ]
