# Generated by Django 5.2.3 on 2025-07-18 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Pełna nazwa firmy')),
                ('tax_id', models.CharField(max_length=20, verbose_name='NIP')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica i numer')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('bank_account_number', models.CharField(max_length=34, verbose_name='Numer konta bankowego')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dane Firmy',
                'verbose_name_plural': 'Dane Firmy',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kontrahenta')),
                ('tax_id', models.CharField(blank=True, help_text='Wypełnij, jeśli dotyczy', max_length=20, null=True, verbose_name='NIP')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica i numer')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'Kontrahenci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numer faktury')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data wystawienia')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data sprzedaży')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kwota całkowita')),
                ('payment_method', models.CharField(choices=[('przelew', 'Przelew'), ('gotówka', 'Gotówka')], default='przelew', max_length=50, verbose_name='Sposób płatności')),
                ('payment_date', models.DateField(verbose_name='Termin płatności')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('is_correction', models.BooleanField(default=False, verbose_name='Czy to korekta?')),
                ('correction_reason', models.TextField(blank=True, null=True, verbose_name='Przyczyna korekty')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ksiegowosc.contractor', verbose_name='Kontrahent')),
                ('corrected_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='ksiegowosc.invoice', verbose_name='Faktura korygowana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa usługi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość')),
                ('unit', models.CharField(default='godz.', max_length=10, verbose_name='J.M.')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jedn.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość')),
                ('lump_sum_tax_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=4, verbose_name='Stawka ryczałtu (%)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ksiegowosc.invoice', verbose_name='Faktura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pozycja na fakturze',
                'verbose_name_plural': 'Pozycje na fakturze',
            },
        ),
        migrations.CreateModel(
            name='MonthlySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Miesiąc')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Przychód w danym miesiącu')),
                ('health_insurance_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Opłacona składka zdrowotna')),
                ('income_tax_payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Należny podatek dochodowy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Rozliczenie miesięczne',
                'verbose_name_plural': 'Rozliczenia miesięczne',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
