# Generated by Django 5.2.3 on 2025-07-19 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ulica i numer'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin płatności'),
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('user', 'tax_id')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlysettlement',
            unique_together={('year', 'month', 'user')},
        ),
    ]
