# Generated by Django 5.2.3 on 2025-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0003_extend_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='kod_urzedu',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Kod urzędu skarbowego'),
        ),
    ]
