# Generated by Django 5.2.3 on 2025-07-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0005_alter_companyinfo_kod_urzedu'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='corrected_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_entries', to='ksiegowosc.invoiceitem', verbose_name='Korygowana pozycja'),
        ),
    ]
