# Generated by Django 5.2.3 on 2025-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0006_invoiceitem_corrected_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='default_labor_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Domyślna składka na Fundusz Pracy'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='default_social_insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Domyślna składka społeczna'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='pays_only_health_insurance',
            field=models.BooleanField(default=True, verbose_name='Płaci tylko składkę zdrowotną (ZUS z umowy o pracę)'),
        ),
        migrations.AddField(
            model_name='monthlysettlement',
            name='labor_fund_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Opłacona składka na Fundusz Pracy'),
        ),
        migrations.AddField(
            model_name='monthlysettlement',
            name='social_insurance_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Opłacona składka społeczna'),
        ),
    ]
