# Generated by Django 5.2.3 on 2025-07-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0007_companyinfo_default_labor_fund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='default_labor_fund',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='default_social_insurance',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='pays_only_health_insurance',
        ),
    ]
