# Generated by Django 5.2.3 on 2025-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0008_remove_companyinfo_default_labor_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='default_labor_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Domyślna składka na Fundusz Pracy'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='default_social_insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Domyślna składka społeczna'),
        ),
    ]
