# Generated by Django 5.2.3 on 2025-07-22 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0009_companyinfo_default_labor_fund_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('total_yearly_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Łączny przychód roczny')),
                ('total_social_insurance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Łączne składki społeczne')),
                ('total_health_insurance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Łączne składki zdrowotne')),
                ('total_labor_fund_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Łączne składki na Fundusz Pracy')),
                ('total_monthly_tax_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Suma podatków z rozliczeń miesięcznych')),
                ('calculated_yearly_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Obliczony podatek roczny')),
                ('tax_difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Różnica (dopłata/zwrot)')),
                ('tax_rate_used', models.DecimalField(decimal_places=2, default=14.0, max_digits=4, verbose_name='Stawka podatku (%)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Rozliczenie roczne',
                'verbose_name_plural': 'Rozliczenia roczne',
                'ordering': ['-year'],
                'unique_together': {('year', 'user')},
            },
        ),
    ]
