# Generated by Django 5.2.3 on 2025-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0010_yearlysettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZUSRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Rok')),
                ('minimum_wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Płaca minimalna')),
                ('minimum_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimalna podstawa wymiaru')),
                ('pension_rate', models.DecimalField(decimal_places=4, default=0.1976, max_digits=5, verbose_name='Stawka emerytalno-rentowa (%)')),
                ('disability_rate', models.DecimalField(decimal_places=4, default=0.015, max_digits=5, verbose_name='Stawka rentowa (%)')),
                ('accident_rate', models.DecimalField(decimal_places=4, default=0.0167, max_digits=5, verbose_name='Stawka wypadkowa (%)')),
                ('labor_fund_rate', models.DecimalField(decimal_places=4, default=0.0245, max_digits=5, verbose_name='Stawka Fundusz Pracy (%)')),
                ('health_insurance_rate', models.DecimalField(decimal_places=4, default=0.09, max_digits=5, verbose_name='Stawka zdrowotna (%)')),
                ('health_insurance_deductible_rate', models.DecimalField(decimal_places=4, default=0.0775, max_digits=5, verbose_name='Stawka zdrowotna odliczalna (%)')),
                ('preferential_pension_rate', models.DecimalField(decimal_places=4, default=0.1976, max_digits=5, verbose_name='Preferencja emerytalno-rentowa (%)')),
                ('preferential_months', models.IntegerField(default=24, verbose_name='Liczba miesięcy preferencji')),
                ('small_zus_plus_threshold', models.DecimalField(decimal_places=2, default=120000, max_digits=12, verbose_name='Próg przychodów Małe ZUS Plus')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, verbose_name='Źródło danych')),
                ('is_current', models.BooleanField(default=False, verbose_name='Aktualne stawki')),
            ],
            options={
                'verbose_name': 'Stawki ZUS',
                'verbose_name_plural': 'Stawki ZUS',
                'ordering': ['-year'],
            },
        ),
    ]
