# Generated by Django 5.2.3 on 2025-07-24 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0011_zusrates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('payment_date', models.DateField(verbose_name='Data płatności')),
                ('payment_method', models.CharField(choices=[('przelew', 'Przelew bankowy'), ('gotowka', 'Gotówka'), ('karta', 'Karta płatnicza'), ('blik', 'BLIK'), ('paypal', 'PayPal'), ('inne', 'Inne')], default='przelew', max_length=20, verbose_name='Sposób płatności')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Numer referencyjny banku')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('completed', 'Zrealizowana'), ('cancelled', 'Anulowana'), ('refunded', 'Zwrócona')], default='completed', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ksiegowosc.invoice', verbose_name='Faktura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
                'ordering': ['-payment_date'],
            },
        ),
    ]
