# Generated by Django 5.2.3 on 2025-07-24 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0012_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('code', models.CharField(max_length=20, verbose_name='Kod kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Kategoria kosztów',
                'verbose_name_plural': 'Kategorie kosztów',
                'ordering': ['name'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Początek okresu')),
                ('period_end', models.DateField(verbose_name='Koniec okresu')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Łączne koszty')),
                ('deductible_expenses', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Koszty uzyskania przychodu')),
                ('vat_to_deduct', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='VAT do odliczenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Raport kosztów',
                'verbose_name_plural': 'Raporty kosztów',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Numer faktury')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('receipt_date', models.DateField(help_text='Kiedy otrzymaliśmy fakturę', verbose_name='Data otrzymania')),
                ('service_date', models.DateField(verbose_name='Data świadczenia usługi/dostawy')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Termin płatności')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota netto')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kwota VAT')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota brutto')),
                ('category', models.CharField(choices=[('materials', 'Materiały i towary'), ('services', 'Usługi'), ('office', 'Koszty biurowe'), ('transport', 'Transport i paliwo'), ('marketing', 'Marketing i reklama'), ('software', 'Oprogramowanie i licencje'), ('equipment', 'Sprzęt i narzędzia'), ('rent', 'Czynsz i najem'), ('utilities', 'Media (prąd, gaz, woda)'), ('insurance', 'Ubezpieczenia'), ('legal', 'Usługi prawne i doradcze'), ('training', 'Szkolenia i rozwój'), ('travel', 'Podróże służbowe'), ('maintenance', 'Naprawy i konserwacja'), ('telecommunications', 'Telekomunikacja'), ('other', 'Inne koszty')], help_text='Rodzaj kosztu', max_length=50, verbose_name='Kategoria')),
                ('is_deductible', models.BooleanField(default=True, verbose_name='Koszt uzyskania przychodu')),
                ('vat_deductible', models.BooleanField(default=True, verbose_name='VAT do odliczenia')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Opłacona')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data zapłaty')),
                ('payment_method', models.CharField(choices=[('transfer', 'Przelew'), ('cash', 'Gotówka'), ('card', 'Karta'), ('other', 'Inne')], default='transfer', max_length=50, verbose_name='Sposób płatności')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='purchase_invoices/', verbose_name='Plik faktury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksiegowosc.expensecategory', verbose_name='Szczegółowa kategoria')),
                ('supplier', models.ForeignKey(help_text='Kontrahent, od którego kupujemy', on_delete=django.db.models.deletion.PROTECT, to='ksiegowosc.contractor', verbose_name='Dostawca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Faktura zakupu',
                'verbose_name_plural': 'Faktury zakupu',
                'ordering': ['-issue_date', '-receipt_date'],
                'unique_together': {('user', 'invoice_number', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa towaru/usługi')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Ilość')),
                ('unit', models.CharField(default='szt.', max_length=10, verbose_name='J.M.')),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jedn. netto')),
                ('vat_rate', models.CharField(choices=[('0', '0%'), ('5', '5%'), ('8', '8%'), ('23', '23%'), ('zw', 'Zwolniony'), ('np', 'Nie podlega')], default='23', max_length=5, verbose_name='Stawka VAT')),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość netto')),
                ('vat_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość VAT')),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość brutto')),
                ('category', models.CharField(blank=True, choices=[('materials', 'Materiały i towary'), ('services', 'Usługi'), ('office', 'Koszty biurowe'), ('transport', 'Transport i paliwo'), ('marketing', 'Marketing i reklama'), ('software', 'Oprogramowanie i licencje'), ('equipment', 'Sprzęt i narzędzia'), ('rent', 'Czynsz i najem'), ('utilities', 'Media (prąd, gaz, woda)'), ('insurance', 'Ubezpieczenia'), ('legal', 'Usługi prawne i doradcze'), ('training', 'Szkolenia i rozwój'), ('travel', 'Podróże służbowe'), ('maintenance', 'Naprawy i konserwacja'), ('telecommunications', 'Telekomunikacja'), ('other', 'Inne koszty')], max_length=50, verbose_name='Kategoria')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ksiegowosc.purchaseinvoice', verbose_name='Faktura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pozycja faktury zakupu',
                'verbose_name_plural': 'Pozycje faktur zakupu',
                'ordering': ['id'],
            },
        ),
    ]
