# Generated by Django 5.2.3 on 2025-07-30 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0014_alter_invoice_options_alter_invoice_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'invoice_number')},
        ),
    ]
