# Generated by Django 5.2.3 on 2025-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksiegowosc", "0015_alter_invoice_options_alter_invoice_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="ksef_environment",
            field=models.CharField(
                choices=[
                    ("test", "Środowisko testowe"),
                    ("prod", "Środowisko produkcyjne"),
                ],
                default="test",
                help_text="Wybierz środowisko, z którym chcesz się integrować.",
                max_length=10,
                verbose_name="Środowisko KSeF",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="ksef_token",
            field=models.CharField(
                blank=True,
                help_text="Wygenerowany w aplikacji KSeF. Będzie bezpiecznie przechowywany.",
                max_length=255,
                verbose_name="Token autoryzacyjny KSeF",
            ),
        ),
    ]
