# Generated by Django 5.2.3 on 2025-10-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksiegowosc", "0016_companyinfo_ksef_environment_companyinfo_ksef_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "verbose_name": "Pozycja faktury",
                "verbose_name_plural": "Pozycje faktur",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="ksef_processing_description",
            field=models.TextField(
                blank=True,
                help_text="Zawiera komunikaty o błędach lub sukcesie z KSeF",
                null=True,
                verbose_name="Opis przetwarzania KSeF",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ksef_reference_number",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Numer referencyjny KSeF",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ksef_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data wysłania do KSeF"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ksef_session_id",
            field=models.CharField(
                blank=True,
                help_text="Numer referencyjny sesji po wysłaniu faktury",
                max_length=40,
                null=True,
                verbose_name="ID sesji KSeF",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ksef_status",
            field=models.CharField(
                blank=True,
                help_text="Status przetwarzania faktury w KSeF (np. Wysłano, Przetworzono, Błąd)",
                max_length=20,
                null=True,
                verbose_name="Status w KSeF",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="corrected_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="ksiegowosc.invoiceitem",
                verbose_name="Pozycja korygowana (stan 'przed korektą')",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="lump_sum_tax_rate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2", "2%"),
                    ("3", "3%"),
                    ("5.5", "5,5%"),
                    ("8.5", "8,5%"),
                    ("10", "10%"),
                    ("12", "12%"),
                    ("14", "14%"),
                    ("15", "15%"),
                    ("17", "17%"),
                    ("20", "20%"),
                ],
                max_length=10,
                null=True,
                verbose_name="Stawka ryczałtu (%)",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nazwa towaru/usługi"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=10, verbose_name="Ilość"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Wartość całkowita"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit",
            field=models.CharField(default="szt.", max_length=10, verbose_name="J.M."),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena jednostkowa"
            ),
        ),
    ]
