# Generated by Django 5.2.3 on 2025-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksiegowosc", "0017_alter_invoiceitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="ksef_status",
            field=models.CharField(
                blank=True,
                help_text="Status przetwarzania faktury w KSeF (np. Wysłano, Przetworzono, Błąd)",
                max_length=50,
                null=True,
                verbose_name="Status w KSeF",
            ),
        ),
    ]
